/** Plain-English definitions of the terms the app uses, for the Library's glossary. */
export const GLOSSARY: [string, string][] = [
  ["After-tax return", "What you keep after paying tax on gains. In a taxable account, frequent trading turns gains into short-term gains taxed at your full income rate, so a strategy can beat buy-and-hold before tax and lose after it."],
  ["Backtest", "Running a strategy's rules over past prices as if you had followed them. It shows what would have happened, not what will; and rules chosen after seeing the history tend to look better than they are."],
  ["Basis point (bp)", "One hundredth of a percent: 50 bps = 0.5%. Trading costs are usually quoted in basis points."],
  ["Benchmark", "What a strategy has to beat to be worth the effort: usually just buying an index fund such as SPY and holding it."],
  ["Block bootstrap", "Reshuffling history in blocks of about a month to see how different the same strategy's results could have looked. The probability of beating SPY comes from it."],
  ["Buy and hold", "Buying once and never trading. Cheap, tax-efficient and hard to beat: the standard every strategy here is measured against."],
  ["CAGR", "Compound annual growth rate: the steady yearly return that would turn the starting amount into the final one."],
  ["Cost basis", "What you paid for a holding, including fees. Your taxable gain is the sale price minus the cost basis."],
  ["Deflated Sharpe ratio", "The chance a strategy's Sharpe ratio is real after allowing for how many configurations were tried. Try enough variations and one looks great by luck alone."],
  ["Drawdown", "A fall from a previous peak. The maximum drawdown is the worst one: a measure of how painful a strategy was to stick with."],
  ["Excess return", "Return above a benchmark's over the same period. Positive means it beat the benchmark."],
  ["Forward test", "Recording a strategy's calls before their outcome exists and scoring them later. Unlike a backtest it cannot be tuned to history, which makes it the only fair test, and a slow one."],
  ["Hit rate", "The share of calls that beat the benchmark. A high hit rate with small wins and large losses can still lose money."],
  ["Independent observations", "Results that do not share any days. Two 21-day windows that start a day apart overlap by 20 days and are nearly the same result, so the journal only counts calls at least 21 sessions apart."],
  ["Long-term capital gain", "A gain on something held more than a year; US federal rates are 0%, 15% or 20%, much lower than on short-term gains."],
  ["Look-ahead bias", "Accidentally using information a trader would not have had at the time, such as today's close to trade at today's open. It makes backtests look far better than reality."],
  ["Overfitting", "Tuning a strategy so closely to past data that it captures noise instead of anything that will repeat."],
  ["Paper trading", "Trading with practice money at a broker. Fills are simulated, so it tests the mechanics and costs, not your nerve."],
  ["Pre-registered rule", "Writing down what will count as success before seeing the results, so the goalposts cannot move afterwards."],
  ["Rebalancing", "Trading back to target weights after prices have moved, for example back to 60% stocks and 40% bonds."],
  ["Sharpe ratio", "Return above T-bills divided by volatility: return per unit of risk. Around 0.5 for the US stock market over the long run."],
  ["Short-term capital gain", "A gain on something held a year or less, taxed like ordinary income (up to 37% federally)."],
  ["Slippage", "The difference between the price you expected and the price you got. The backtests assume 5 bps per trade."],
  ["Survivorship bias", "Testing only on companies that still exist today, which leaves out the ones that failed and flatters any strategy."],
  ["T-bills", "Short-term US government debt: the 'risk-free' return that idle cash can earn. Strategies here earn it on cash they are not using."],
  ["Tax-loss harvesting", "Selling a holding at a loss to offset taxable gains, then buying something similar but not 'substantially identical' so you stay invested."],
  ["t-statistic", "How many standard errors an average is from zero. Below about 2 the result is easily luck; with many results on one page, demand 3."],
  ["Walk-forward test", "Choosing a strategy's settings using only data before each test period, then testing on the period after. It keeps the test data unseen."],
  ["Wash sale", "Selling at a loss and buying the same or a substantially identical security within 30 days before or after: the IRS disallows the loss for now."],
];
